# Steamy will run the launcher_exec command when the first controller connects.
# The name and icons are used in notifications.

# Comment out to disable automatic launch
launcher_exec=("/usr/bin/steam-native" "-bigpicture")
launcher_name="Steam"

launcher_icon="/usr/share/steamy/icons/transparent-steam.png"
controller_icon="/usr/share/steamy/icons/transparent-controller.png"
